name: main

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  unit:
    name: "Unit and mutation testing"
    runs-on: ${{ matrix.os }}
    continue-on-error: true

    strategy:
      matrix:
        os: [ "ubuntu-latest" ]
        php-version: [ "7.4", "8.0", "8.1" ]

    env:
      COMPOSER_VERSION: 2
      MINIMUM_COVERAGE_PERCENTAGE: 80
      MINIMUM_MSI_PERCENTAGE: 80

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: ${{ env.COVERAGE_DRIVER }}
          ini-values: memory_limit=512M, xdebug.mode=off
          tools: composer:${{ env.COMPOSER_VERSION }}

      - name: Get Composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Restore Composer cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: composer-${{ runner.os }}-${{ matrix.php-version }}-${{ hashFiles('composer.*') }}
          restore-keys: composer-${{ runner.os }}-${{ matrix.php-version }}-

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist --no-progress

      - name: Run unit tests
        run: |
          XDEBUG_MODE=coverage php vendor/bin/phpunit --testsuite unit
          php vendor/bin/coverage-check coverage/clover.xml ${{ env.MINIMUM_COVERAGE_PERCENTAGE }}

      - name: Run mutation tests
        run: XDEBUG_MODE=coverage php vendor/bin/infection --show-mutations --min-msi=${{ env.MINIMUM_MSI_PERCENTAGE }} --threads=4

  lint:
    name: "Linting"
    runs-on: ${{ matrix.os }}
    continue-on-error: true

    strategy:
      matrix:
        os: [ "ubuntu-latest" ]
        php-version: [ "8.1" ]

    env:
      COMPOSER_VERSION: 2
      PHP_CS_FIXER_CACHE_FILE: .php-cs-fixer.cache

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}

      - name: Get Composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Restore Composer cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: composer-${{ runner.os }}-${{ matrix.php-version }}-${{ hashFiles('composer.*') }}
          restore-keys: composer-${{ runner.os }}-${{ matrix.php-version }}-

      - name: Install dependencies
        run: |
          composer install --no-interaction --prefer-dist --no-progress

      - name: Run PHP-CS-Fixer
        run: php vendor/bin/php-cs-fixer fix --config .php-cs-fixer.dist.php --verbose --dry-run
