name: main

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  unit:
    name: "Unit tests for PHP ${{ matrix.php-version }}"
    runs-on: ${{ matrix.os }}
    continue-on-error: true

    strategy:
      matrix:
        os: ["ubuntu-latest"]
        php-version: ["7.4", "8.0", "8.1", "latest"]

    env:
      COMPOSER_VERSION: 2

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        uses: php-actions/composer@v6
        with:
          php_version: ${{ matrix.php-version }}
          version: ${{ env.COMPOSER_VERSION }}

      - name: Run unit tests
        uses: php-actions/phpunit@v3
        with:
          configuration: phpunit.xml.dist
          php_version: ${{ matrix.php-version }}
          args: --testsuite "Unit"
