on: [ push, pull_request ]
name: Lint
jobs:
  php-cs-fixer:
    name: "php-cs-fixer"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "PHP-CS-Fixer"
        uses: docker://oskarstark/php-cs-fixer-ga:3.6.0
        with:
          args: --dry-run --rules="@PSR12,align_multiline_comment,array_indentation,blank_line_before_statement,no_unused_imports,no_useless_else,no_useless_return,ordered_imports,phpdoc_scalar,return_assignment,simplified_if_return,trailing_comma_in_multiline"
